# <div style="text-align: center; color: cyan">Tensor</div>

## <div style="text-align: center; color: lime">Imports</div>

In [2]:
import torch

## <div style="text-align: center; color: lime">Create a Tensor</div>

In [3]:
data = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
]
t1 = torch.tensor(data)
print(t1)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [8]:
s1 = torch.rand((3, 8))
print(s1)
print(s1.shape)

tensor([[0.6667, 0.7057, 0.7670, 0.7719, 0.7298, 0.5729, 0.8281, 0.5963],
        [0.1056, 0.5377, 0.3380, 0.4923, 0.0246, 0.8192, 0.3945, 0.1150],
        [0.3885, 0.4211, 0.2655, 0.6766, 0.5082, 0.6465, 0.9499, 0.2008]])
torch.Size([3, 8])


In [9]:
s2 = torch.zeros((3, 8))
print(s2)
print(s2.shape)

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])
torch.Size([3, 8])


In [10]:
s3 = torch.ones((3, 8))
print(s3)
print(s3.shape)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])
torch.Size([3, 8])


In [11]:
l1 = torch.zeros_like(t1)
print(l1)
print(l1.shape)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.Size([3, 3])


## <div style="text-align: center; color: lime">Tensor Attributes</div>

In [12]:
print(f"shape: {t1.shape}")
print(f"dtype: {t1.dtype}")
print(f"device: {t1.device}")

shape: torch.Size([3, 3])
dtype: torch.int64
device: cpu


## <div style="text-align: center; color: lime">Control the device</div>

In [13]:
if torch.accelerator.is_available():
    device = torch.accelerator.current_accelerator()
else:
    device = "cpu"

print(device)

mps


In [14]:
t1 = t1.to(device)
print(t1.device)

mps:0


<div style="text-align: center">

<div>
    @LiterallyTheOne — PhD Candidate in Artificial Intelligence
</div>

<a style="margin: 1em" href="https://literallytheone.github.io">
https://literallytheone.github.io
</a>

</div>
