# <div style="text-align: center; color: cyan">Tensor</div>

## <div style="text-align: center; color: lime">Imports</div>

In [2]:
import torch

## <div style="text-align: center; color: lime">Create a Tensor</div>

In [3]:
data = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
]
t1 = torch.tensor(data)
print(t1)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [4]:
s1 = torch.rand((3, 8))
print(s1)
print(s1.shape)

tensor([[0.5226, 0.6391, 0.0536, 0.5870, 0.7463, 0.8882, 0.0854, 0.9113],
        [0.6659, 0.3923, 0.7082, 0.8238, 0.1705, 0.3672, 0.9563, 0.4498],
        [0.7385, 0.5925, 0.6865, 0.2962, 0.0998, 0.8313, 0.2338, 0.9663]])
torch.Size([3, 8])


In [5]:
s2 = torch.zeros((3, 8))
print(s2)
print(s2.shape)

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])
torch.Size([3, 8])


In [6]:
s3 = torch.ones((3, 8))
print(s3)
print(s3.shape)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])
torch.Size([3, 8])


In [7]:
l1 = torch.zeros_like(t1)
print(l1)
print(l1.shape)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.Size([3, 3])


## <div style="text-align: center; color: lime">Tensor Attributes</div>

In [8]:
print(f"shape: {t1.shape}")
print(f"dtype: {t1.dtype}")
print(f"device: {t1.device}")

shape: torch.Size([3, 3])
dtype: torch.int64
device: cpu


## <div style="text-align: center; color: lime">Control the device</div>

In [9]:
if torch.accelerator.is_available():
    device = torch.accelerator.current_accelerator()
else:
    device = "cpu"

print(device)

mps


In [10]:
t1 = t1.to(device)
print(t1.device)

mps:0


## <div style="text-align: center; color: lime">Operations on Tensor</div>

In [14]:
print(t1)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], device='mps:0')


In [11]:
t1_first_row = t1[0]
print(t1_first_row)

tensor([1, 2, 3], device='mps:0')


In [12]:
t1_first_column = t1[:, 0]
print(t1_first_column)

tensor([1, 4, 7], device='mps:0')


In [13]:
t1_slice = t1[1:, 1:]
print(t1_slice)

tensor([[5, 6],
        [8, 9]], device='mps:0')


In [16]:
c1 = torch.zeros((5, 4))
c2 = torch.ones((5, 2))

c3 = torch.concat((c1, c2), dim=1)
print(c3)

tensor([[0., 0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1., 1.]])


In [17]:
a1 = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
])
a1t = a1.T

print(a1)
print(a1t)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [20]:
matrix_1 = torch.Tensor([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
])

matrix_2 = torch.tensor([
    [1.0],
    [2.0],
    [3.0],
])

result = matrix_1 @ matrix_2
print(result)

tensor([[14.],
        [32.]])


In [21]:
sum_matrix_1 = matrix_1.sum()
print(sum_matrix_1)

tensor(21.)


In [25]:
b1 = torch.tensor([
    [3, 1, 7, 2],
    [2, 4, 1, 3],
    [9, 1, 2, 5],
])

max_of_each_row = b1.max(dim=1)

print(max_of_each_row)

torch.return_types.max(
values=tensor([7, 4, 9]),
indices=tensor([2, 1, 0]))


In [26]:
argmax_of_each_row = b1.argmax(dim=1)

print(argmax_of_each_row)

tensor([2, 1, 0])


<div style="text-align: center">

<div>
    @LiterallyTheOne — PhD Candidate in Artificial Intelligence
</div>

<a style="margin: 1em" href="https://literallytheone.github.io">
https://literallytheone.github.io
</a>

</div>
