<div style="text-align: center">
    <a
     href="https://colab.research.google.com/github/LiterallyTheOne/Pytorch_Tutorial/blob/main/src/2_model.ipynb"
     target="_parent">
        <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
    </a>
</div>


# <div style="text-align: center; color: cyan">Model</div>

## <div style="text-align: center; color: lime">Imports</div>

In [2]:
import torch
from torch import nn

## <div style="text-align: center; color: lime">Sequential</div>

In [3]:
model_2 = nn.Sequential(
    nn.Linear(8, 16),
    nn.Linear(16, 4),
)

In [4]:
data = torch.rand((3, 8))
result = model_2(data)

print(result)

tensor([[ 0.4628,  0.2211,  0.0679, -0.1155],
        [ 0.5002,  0.1515, -0.0235, -0.2743],
        [ 0.3082,  0.1182, -0.0379, -0.2231]], grad_fn=<AddmmBackward0>)


In [5]:
model_3 = nn.Sequential(
    nn.Linear(8, 16),
    nn.Linear(16, 32),
    nn.Linear(32, 4),
)

In [6]:
data = torch.rand((3, 8))
result = model_3(data)

print(result)

tensor([[ 0.1217,  0.0501,  0.0438, -0.0664],
        [ 0.0818,  0.1063,  0.0646, -0.0404],
        [ 0.1090,  0.1851,  0.1897, -0.0982]], grad_fn=<AddmmBackward0>)


## <div style="text-align: center; color: lime">Standard way of defining a model</div>

In [7]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.layers = nn.Sequential(
            nn.Linear(8, 16),
            nn.Linear(16, 32),
            nn.Linear(32, 4),
        )

    def forward(self, x):
        x = self.layers(x)
        return x


In [8]:
my_model = MyModel()

print(my_model)

MyModel(
  (layers): Sequential(
    (0): Linear(in_features=8, out_features=16, bias=True)
    (1): Linear(in_features=16, out_features=32, bias=True)
    (2): Linear(in_features=32, out_features=4, bias=True)
  )
)


In [9]:
data = torch.rand((3, 8))

result = my_model(data)
print(result)

tensor([[ 0.0029, -0.1755, -0.0807, -0.0575],
        [ 0.0041, -0.1062, -0.1004,  0.0481],
        [ 0.0467, -0.1093, -0.1092,  0.0350]], grad_fn=<AddmmBackward0>)


In [10]:
class MyModel2(nn.Module):
    def __init__(self):
        super().__init__()

        self.layers_1 = nn.Sequential(
            nn.Linear(8, 16),
            nn.Linear(16, 32),
        )

        self.layers_2 = nn.Sequential(
            nn.Linear(32, 16),
            nn.Linear(16, 4),
        )

    def forward(self, x):
        x = self.layers_1(x)
        x = self.layers_2(x)
        return x


In [11]:
my_model_2 = MyModel2()

print(my_model_2)

MyModel2(
  (layers_1): Sequential(
    (0): Linear(in_features=8, out_features=16, bias=True)
    (1): Linear(in_features=16, out_features=32, bias=True)
  )
  (layers_2): Sequential(
    (0): Linear(in_features=32, out_features=16, bias=True)
    (1): Linear(in_features=16, out_features=4, bias=True)
  )
)


In [12]:
data = torch.rand((3, 8))

result = my_model_2(data)
print(result)


tensor([[ 0.0159,  0.0748, -0.0380,  0.0950],
        [ 0.0352,  0.0939, -0.1671,  0.0441],
        [ 0.0777,  0.0626, -0.0552,  0.0902]], grad_fn=<AddmmBackward0>)


## <div style="text-align: center; color: lime">Run on accelerator</div>

In [13]:
if torch.accelerator.is_available():
    device = torch.accelerator.current_accelerator()
else:
    device = "cpu"

print(device)


mps


In [14]:
data = torch.rand((3, 8))
my_model_2 = MyModel2()

data = data.to(device)
my_model_2 = my_model_2.to(device)

result = my_model_2(data)

print(result)

tensor([[ 0.1318,  0.0968, -0.0257, -0.3693],
        [ 0.0812,  0.0943, -0.0765, -0.4375],
        [ 0.1081,  0.0463, -0.0657, -0.4549]], device='mps:0',
       grad_fn=<LinearBackward0>)


<div style="text-align: center">

<div>
    @LiterallyTheOne — PhD Candidate in Artificial Intelligence
</div>

<a style="margin: 1em" href="https://literallytheone.github.io">
https://literallytheone.github.io
</a>

</div>
