# <div style="text-align: center; color: cyan">Data</div>

## <div style="text-align: center; color: lime">Imports</div>

In [1]:
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader, random_split

import numpy as np

from sklearn.datasets import load_iris

## <div style="text-align: center; color: lime">Load iris</div>

In [2]:
iris = load_iris()

In [3]:
print("feature names:")
print(iris.feature_names)

feature names:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [4]:
print("target names:")
print(iris.target_names)

target names:
['setosa' 'versicolor' 'virginica']


In [5]:
print("Number of samples:", len(iris.data))

Number of samples: 150


In [6]:
chosen_indexes = np.linspace(0, len(iris.data), 10, dtype=int, endpoint=False)
print("Chosen indices:")
print(chosen_indexes)
print()

print("10 samples of data:")
print(iris.data[chosen_indexes])
print()

print("10 samples of target:")
print(iris.target[chosen_indexes])
print()

Chosen indices:
[  0  15  30  45  60  75  90 105 120 135]

10 samples of data:
[[5.1 3.5 1.4 0.2]
 [5.7 4.4 1.5 0.4]
 [4.8 3.1 1.6 0.2]
 [4.8 3.  1.4 0.3]
 [5.  2.  3.5 1. ]
 [6.6 3.  4.4 1.4]
 [5.5 2.6 4.4 1.2]
 [7.6 3.  6.6 2.1]
 [6.9 3.2 5.7 2.3]
 [7.7 3.  6.1 2.3]]

10 samples of target:
[0 0 0 0 1 1 1 2 2 2]



## <div style="text-align: center; color: lime">Make the data Ready for the model</div>

In [7]:
data = torch.tensor(iris.data).to(torch.float)
target = torch.tensor(iris.target)

In [8]:
class IRISClassifier(nn.Module):
    def __init__(self):
        super().__init__()

        self.layers = nn.Sequential(
            nn.Linear(4, 16),
            nn.Linear(16, 8),
            nn.Linear(8, 3),
        )

    def forward(self, x):
        return self.layers(x)

In [9]:
iris_classifier = IRISClassifier()
print(iris_classifier)

IRISClassifier(
  (layers): Sequential(
    (0): Linear(in_features=4, out_features=16, bias=True)
    (1): Linear(in_features=16, out_features=8, bias=True)
    (2): Linear(in_features=8, out_features=3, bias=True)
  )
)


In [10]:
logits = iris_classifier(data[chosen_indexes])
print(logits)

tensor([[ 0.3493, -0.0846,  0.4198],
        [ 0.5022, -0.1994,  0.4199],
        [ 0.3048, -0.0376,  0.4019],
        [ 0.3105, -0.0510,  0.3975],
        [ 0.4945, -0.0451,  0.3045],
        [ 0.8255, -0.2312,  0.3319],
        [ 0.6529, -0.1148,  0.2847],
        [ 1.1501, -0.3298,  0.2732],
        [ 1.0917, -0.3530,  0.2194],
        [ 1.1785, -0.3770,  0.2699]], grad_fn=<AddmmBackward0>)


In [11]:
predictions = logits.argmax(dim=1)
for prediction, true_label in zip(predictions, target[chosen_indexes]):
    print(prediction.item(), true_label.item())

2 0
0 0
2 0
2 0
0 1
0 1
0 1
0 2
0 2
0 2


## <div style="text-align: center; color: lime">Dataset</div>

In [12]:
class IRISDataset(Dataset):
    def __init__(self, data, target):
        super().__init__()
        self.data = data
        self.target = target

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx], self.target[idx]

In [13]:
iris_dataset = IRISDataset(data, target)

In [14]:
for one_data, one_target in iris_dataset:
    print(one_data)
    print(one_target)
    break

tensor([5.1000, 3.5000, 1.4000, 0.2000])
tensor(0)


## <div style="text-align: center; color: lime">DataLoader</div>

In [15]:
iris_loader = DataLoader(iris_dataset, batch_size=10, shuffle=True)

In [16]:
for batch_of_data, batch_of_target in iris_loader:
    print(batch_of_data)
    print(batch_of_target)
    break

tensor([[6.5000, 2.8000, 4.6000, 1.5000],
        [6.6000, 3.0000, 4.4000, 1.4000],
        [6.7000, 3.0000, 5.2000, 2.3000],
        [6.1000, 3.0000, 4.9000, 1.8000],
        [7.7000, 2.6000, 6.9000, 2.3000],
        [4.9000, 3.0000, 1.4000, 0.2000],
        [6.3000, 2.5000, 5.0000, 1.9000],
        [6.6000, 2.9000, 4.6000, 1.3000],
        [5.1000, 3.5000, 1.4000, 0.3000],
        [5.8000, 2.7000, 4.1000, 1.0000]])
tensor([1, 1, 2, 2, 2, 0, 2, 1, 0, 1])


## <div style="text-align: center; color: lime">Train, Validation, Test data</div>

In [17]:
g1 = torch.Generator().manual_seed(20)
train_data, val_data, test_data = random_split(iris_dataset, [0.7, 0.2, 0.1], g1)

In [18]:
print("train_data length:", len(train_data))
print("val_data length:", len(val_data))
print("test_data length:", len(test_data))

train_data length: 105
val_data length: 30
test_data length: 15


In [19]:
train_loader = DataLoader(train_data, batch_size=10, shuffle=True)
val_loader = DataLoader(val_data, batch_size=10, shuffle=False)
test_loader = DataLoader(test_data, batch_size=10, shuffle=False)

In [20]:
for batch_of_data, batch_of_target in train_loader:
    logits = iris_classifier(batch_of_data)

    predictions = logits.argmax(dim=1)
    for prediction, true_label in zip(predictions, batch_of_target):
        print(prediction.item(), true_label.item())
    break

2 0
0 2
0 1
2 0
0 1
0 1
0 1
0 2
0 1
0 1


<div style="text-align: center">

<div>
    @LiterallyTheOne — PhD Candidate in Artificial Intelligence
</div>

<a style="margin: 1em" href="https://literallytheone.github.io">
https://literallytheone.github.io
</a>

</div>
