# <div style="text-align: center; color: cyan">Data</div>

## <div style="text-align: center; color: lime">Imports</div>

In [24]:
import torch
from torch import nn

import numpy as np

from sklearn.datasets import load_iris

## <div style="text-align: center; color: lime">Load iris</div>

In [ ]:
iris = load_iris()

In [58]:
print("feature names:")
print(iris.feature_names)

feature names:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [59]:
print("target names:")
print(iris.target_names)

target names:
['setosa' 'versicolor' 'virginica']


In [60]:
print("Number of samples:", len(iris.data))

Number of samples: 150


In [62]:
chosen_indexes = np.linspace(0, len(iris.data), 10, dtype=int, endpoint=False)
print("Chosen indices:")
print(chosen_indexes)
print()

print("10 samples of data:")
print(iris.data[chosen_indexes])
print()

print("10 samples of target:")
print(iris.target[chosen_indexes])
print()

Chosen indices:
[  0  15  30  45  60  75  90 105 120 135]

10 samples of data:
[[5.1 3.5 1.4 0.2]
 [5.7 4.4 1.5 0.4]
 [4.8 3.1 1.6 0.2]
 [4.8 3.  1.4 0.3]
 [5.  2.  3.5 1. ]
 [6.6 3.  4.4 1.4]
 [5.5 2.6 4.4 1.2]
 [7.6 3.  6.6 2.1]
 [6.9 3.2 5.7 2.3]
 [7.7 3.  6.1 2.3]]

10 samples of target:
[0 0 0 0 1 1 1 2 2 2]



## <div style="text-align: center; color: lime">Make the data Ready for the model</div>

In [46]:
data = torch.tensor(iris.data).to(torch.float)
target = torch.tensor(iris.target).to(torch.float)

In [52]:
class IRISClassifier(nn.Module):
    def __init__(self):
        super().__init__()

        self.layers = nn.Sequential(
            nn.Linear(4, 16),
            nn.Linear(16, 8),
            nn.Linear(8, 3),
        )

    def forward(self, x):
        return self.layers(x)

In [53]:
iris_classifier = IRISClassifier()
print(iris_classifier)

IRISClassifier(
  (layers): Sequential(
    (0): Linear(in_features=4, out_features=16, bias=True)
    (1): Linear(in_features=16, out_features=8, bias=True)
    (2): Linear(in_features=8, out_features=3, bias=True)
  )
)


In [63]:
logits = iris_classifier(data[chosen_indexes])
print(logits)

tensor([[ 0.7939, -0.1909,  0.1670],
        [ 0.8980, -0.1740,  0.1619],
        [ 0.7493, -0.1995,  0.1764],
        [ 0.7270, -0.2024,  0.1689],
        [ 0.7400, -0.2674,  0.1978],
        [ 0.9774, -0.2836,  0.1797],
        [ 0.8546, -0.2658,  0.2126],
        [ 1.1355, -0.3332,  0.1992],
        [ 1.0169, -0.2975,  0.2015],
        [ 1.1078, -0.3330,  0.1814]], grad_fn=<AddmmBackward0>)


In [64]:
predictions = logits.argmax(dim=1)
for prediction, true_label in zip(predictions, target[chosen_indexes]):
    print(prediction.item(), true_label.item())

0 0.0
0 0.0
0 0.0
0 0.0
0 1.0
0 1.0
0 1.0
0 2.0
0 2.0
0 2.0


## <div style="text-align: center; color: lime">Dataset</div>

<div style="text-align: center">

<div>
    @LiterallyTheOne — PhD Candidate in Artificial Intelligence
</div>

<a style="margin: 1em" href="https://literallytheone.github.io">
https://literallytheone.github.io
</a>

</div>
